"""Regenerate src/data/strokes.ts from KanjiVG: npm run strokes"""
import json, re, urllib.error, urllib.request

# Pinned, so a change upstream can't alter the strokes; bump it to take newer files.
KANJIVG_SHA = '70a0b7ae0c18ceb5cb358274b029cce0234a43bc'
URL = f'https://raw.githubusercontent.com/KanjiVG/kanjivg/{KANJIVG_SHA}/kanji/{{:05x}}.svg'
# Every character isKana (src/lib/romaji.ts) gives a writing cell: ァ..ヺ and ー.
CHARS = [chr(c) for c in range(0x30A1, 0x30FB)] + ['ー']

PATH = re.compile(r'<path[^>]*?id="kvg:[^"]*-s(\d+)"[^>]*?\sd="([^"]+)"')
NUMBER = re.compile(r'matrix\(1 0 0 1 ([\d.]+) ([\d.]+)\)">(\d+)<')

strokes, missing = {}, []
for ch in CHARS:
    try:
        svg = urllib.request.urlopen(URL.format(ord(ch))).read().decode('utf-8')
    except urllib.error.HTTPError as e:
        if e.code != 404: raise
        missing.append(ch)   # the writing cell falls back to the plain glyph
        continue
    p = [d for _, d in sorted(((int(s), d) for s, d in PATH.findall(svg)))]
    n = [[float(x), float(y)] for x, y, _ in sorted(NUMBER.findall(svg), key=lambda m: int(m[2]))]
    assert p and len(p) == len(n), (ch, len(p), len(n))
    strokes[ch] = {'p': p, 'n': n}

with open('src/data/strokes.ts', 'w', encoding='utf-8') as f:
    f.write('// Katakana stroke order: each character\'s strokes in order (`p`, SVG path data in a 109×109\n')
    f.write('// box) and where each stroke\'s number goes (`n`).\n')
    f.write(f'// From KanjiVG (https://kanjivg.tagaini.net) at commit {KANJIVG_SHA},\n')
    f.write('// © Ulrich Apel, CC BY-SA 3.0. Generated by scripts/build-strokes.py; do not edit by hand.\n')
    f.write('export interface Strokes { p: string[]; n: [number, number][] }\n\n')
    f.write('export const STROKES: Readonly<Record<string, Strokes>> = {\n')
    for ch, s in strokes.items():
        f.write(f'  {json.dumps(ch, ensure_ascii=False)}: {json.dumps(s, separators=(",", ":"))},\n')
    f.write('}\n')
print(f'wrote {len(strokes)} characters; not in KanjiVG: {" ".join(missing) or "none"}')
